services:
  - type: web
    name: apna-bazar-digital
    env: python
    region: singapore # Options: oregon, ohio, frankfurt, singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: MONGO_URI
        sync: false
